//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTemplate.Databse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recept
    {
        public int IdRecept { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> MaterialCount { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
